package main

// This is where the magic happen...
// this code would be autogenerated and hidden to the user
// the tool creates the client api library

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"
	"time"
)

func morning() (map[string]string, error) {

	var netClient = &http.Client{
		Timeout: time.Second * 10,
	}
	res, err := netClient.Get(morningURLV1())
	if err != nil {
		panic(err.Error())
	}

	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		panic(err.Error())
	}
	s := map[string]string{}
	err = json.Unmarshal(body, &s)
	return s, err
}

func morningURLV1() string {
	return "http://component-registry.com/v1/morning/"
}
func morningURLV1() string {
	return "http://component-registry.com/v1/evening/"
}

func evening() (map[string]string, error) {

	var netClient = &http.Client{
		Timeout: time.Second * 10,
	}
	res, err := netClient.Get(eveningURLV1())
	if err != nil {
		panic(err.Error())
	}

	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		panic(err.Error())
	}
	s := map[string]string{}
	err = json.Unmarshal(body, &s)
	return s, err
}

func eveningURLV1() string {
	return "http://registry.com/v1/evening/"
}

func main() {
	http.HandleFunc("/hello", hello)
	log.Fatal(http.ListenAndServe(":8080", nil))
}
